# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Jack Reed"
description: > # this means to ignore newlines until "email:"
   An Agile enthusiast & Scrum Master working in London at Legal & General

email: jack.ross.reed@gmail.com
#blog logo
logo: "/assets/images/blog-logo.png"
float_logo: false # true, false (default)

# blog cover
cover: "/assets/images/background-image.jpg"

name: 'Jack Reed'
author: 'Jack Reed'
author_image: "/assets/images/author.png"

paginate:	5

url: "http://jackreed.es" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@jackrossreed'

#fill in disqus shortname to use disqus
disqus: jackreed
    
google_analytics: UA-122085547-1

# social icons and sharing options
social:
  - icon:	twitter
    url:  https://twitter.com/jackrossreed
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="
    
  - icon:	linkedin
    url:  https://www.linkedin.com/in/jrossreed
    desc: Connect with me on linkedin
    share_url: https://www.linkedin.com/cws/share?url=
    share_title:
    share_link:

 - icon:	instagram
    url:  https://www.instagram.com/jack.ross.reed
    desc: Connect with me on instagram
    share_url: https://www.instagram.com/share
    share_title:
    share_link:
    
  #- icon:	facebook
    url: https://facebook.com/jack.ross.reed
    desc: Connect with me on facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
    url: https://github.com/IamJackReed
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  #- icon:	google-plus
    #url:	https://plus.google.com/103467642514641444562
    #desc:	Follow me on google+
    #share_url:
    #share_title:
    #share_link:
    
